### ISSUE TITLE
Enter cause crash

### ISSUE THREAD

**Issue by goosesima** [noisersup/ledyt#1]
If search bar empty it cause crash
`
panic: runtime error: index out of range [0] with length 0

goroutine 193 [running]:
main.model.Update.func2()
        /home/sima/ledyt/main.go:153 +0x411
created by main.model.Update
        /home/sima/ledyt/main.go:140 +0x88a
`

**Comment by goosesima** [comment]
Fix:
https://github.com/noisersup/ledyt/pull/2

**Comment by noisersup** [comment]
Thank you once again!
Your PR solved an issue so I'm closing
